/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://tcfuvvz7dvfe5ajargaku7pj7a.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-azzsqy4kwnhz5muzwif6ix5zuq",
    "aws_cognito_identity_pool_id": "us-east-2:d6995a17-274d-4402-958d-345181f3ba98",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_3VyrUt6Ro",
    "aws_user_pools_web_client_id": "1nocrjhb12a1s79ibr7tf35sc7",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
